language: python
dist: xenial
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=precommit
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=mypy
    - python: 3.7
      env: TOXENV=black
    - python: 3.7
      env: TOXENV=isort
    - python: 3.7
      env: TOXENV=doc8
cache: pip
install:
  - pip install -U pip wheel setuptools
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov
