language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
cache: pip
install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run -m pytest
after_success:
  - codecov
